apiVersion: v1
kind: Service
metadata:
  name: inteniquetic-service
  labels:
    app: inteniquetic
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: inteniquetic
  type: LoadBalancer
